### ISSUE TITLE
Switch requests

### ISSUE THREAD

**Issue by bseditor** [FireFighter1027/ba_1.6#1]
Hey there first of all awesome scripts, but I have something which you may want to work on:
How about:
1. Making a switch to enable/disable chat logs.
2. Making a switch to enable/disable the checking, whether a player joins the game or not to enable/disable a player to send messages without joining the game.

**Comment by nk2nithish** [comment]
.

I am sorry, but i left modding related stuff many months ago...
you can use any of my codes to develop yours...
